services:
  - type: web
    name: login-game-project
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/login-game-project-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/java
